project_id = "okertqaojhjafezdwnaa"

[functions.fetch-catalogo]
verify_jwt = false

[functions.proxy-image]
verify_jwt = false

[functions.fetch-products]
verify_jwt = false

[functions.fetch-order-details]
verify_jwt = false

[functions.fetch-product-details]
verify_jwt = false

[functions.fetch-dashboard]
verify_jwt = false

[functions.fetch-item-reports]
verify_jwt = false

[functions.fetch-reps]
verify_jwt = false

[functions.fetch-orders]
verify_jwt = false

[functions.fetch-clients]
verify_jwt = false

[functions.fetch-charges]
verify_jwt = false

[functions.fetch-analytics]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.fetch-rep-reports]
verify_jwt = false
